### ISSUE TITLE
global name 'pq_out' is not defined in evpi.py

### ISSUE THREAD

**Issue by lidra** [raosudha89/ranking_clarification_questions#2]
Hi, ransudha89.
in evpi.py, where is 'pq_out' defined?
Did you run you code sucessfully?

**Comment by raosudha89** [comment]
Hi lidra,

I made some last minute changes in the variable names to make it more interpretable. I will rerun the code on my side to make sure it works with the changes. I will update you once I do a dry-run.

Thanks
Sudha

**Comment by raosudha89** [comment]
Hi lidra,

I fixed this (and some other issues) and I am able to successfully run it now. Please let me know if you face any issues.

Thanks
Sudha

**Comment by raosudha89** [comment]
Closing this issue. Please open a new one if you face any further problems.
