### ISSUE TITLE
src/models/run_load_data.sh failed to run 

### ISSUE THREAD

**Issue by qtli** [raosudha89/ranking_clarification_questions#3]
sh src/models/run_load_data.sh

Namespace(no_of_candidates=10, post_data_tsv='data/superuser.com/post_data.tsv', qa_data_tsv='data/superuser.com/qa_data.tsv', test_ids='data/superuser.com/test_ids', train_ids='data/superuser.com/train_ids', tune_ids='data/superuser.com/tune_ids', vocab='embeddings/vocab.p')

Traceback (most recent call last):
  File "src/models/load_data.py", line 82, in <module>
    main(args)
  File "src/models/load_data.py", line 61, in main
    train_ids = read_ids(args.train_ids)
  File "src/models/load_data.py", line 37, in read_ids
    ids = [curr_id.strip('\n') for curr_id in open(ids_file, 'r').readlines().split()]
AttributeError: 'list' object has no attribute 'split'

I don't know what to do, I hope I can have a suggestion. thank you very much

**Comment by raosudha89** [comment]
Hi,

Can you pull the latest version of the code? There were some minor issues that I fixed in my latest commit. If you pull the latest version, this issue should be fixed. Let me know if you still run into any issue.

Thanks
Sudha
